### PR TITLE
Remove composer autoload settings

### PR DESCRIPTION
**Pull request by prolic**
As these are only stub classes, we should not add them to composers autoload mechanism.

### CODE REVIEW

**Comment by empi89** [comment]
Because the constants aren't available otherwise.

**Comment by prolic** [comment]
Okay, but please remove the psr-0 autoloading stuff however ;)

**Comment by empi89** [comment]
I am using this stubs (iirc) within unit tests on machines that do not have php-amqp installed. There I need to be able to use  e.g.new AMQPQueue. Are you using this stubs for autocompletion within your IDE only? Maybe you could require this stubs only with require-dev?

**Comment by prolic** [comment]
Okay, I can understand this. Closing now. Thanks! ;)

**Pull request closed without merging**
